[package]
name = "anony-box-backbone"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
axum = "0.7.7"
diesel = { version = "2.2.4", features = ["postgres", "r2d2", "chrono"] }
chrono = "0.4.38"
dotenvy = "0.15.7"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.64"
